spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5432/urlshortner
spring.datasource.username=postgres
spring.datasource.password=UrlShortnerDev_2026!

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.data.redis.host=localhost
spring.data.redis.port=6379